name: "Godot Tests (GUT)"

on: push

jobs:
  gut-tests:
    name: GUT Tests
    runs-on: ubuntu-latest
    container:
      image: docker://barichello/godot-ci:3.4.4

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run Tests
        run : |
          alias gut="godot -d -s --path $PWD addons/gut/gut_cmdln.gd"
          gut -gexit
